### ISSUE TITLE
Missing license.

### ISSUE THREAD

**Issue by Rubonnek** [RandyGaul/memfile#1]
I'd like to use this software, but without an explicit license it's impossible to tell if I can.

**Comment by RandyGaul** [comment]
Oh okay, let me try and make this zlib. Would that work?

**Comment by RandyGaul** [comment]
Added. Feel free to re-open an issue or comment here if you need anything else.

**Comment by Rubonnek** [comment]
Thanks! The zlib license is perfect for my purpose.
